### PR TITLE
Reconnect on nonfatal error does not close

### PR DESCRIPTION
**Pull request by kohtala**
npm audit reported vulnerabilities in dependencies. Upgrade of mocha [changed mocha behavior](https://boneskull.com/mocha-v4-nears-release/#mochawontforceexit) to not terminate after tests until all asynchronous tasks are completed. It revealed tests that leave something asynchronous behind.

One was an unclosed client in test case, but the other shows failure to close a client that is reconnecting due to nonfatal error. Without the change in `lib/connection.js` the client was left reconnecting after a `.close()` in the test case.

I did the quick fix in `lib/connection.js`, but I think it is a hack and not a correct solution. The `EndpointState` now uses `was_open` and `closed_with_non_fatal_error` on connection to handle some cases for remote closes. To handle also the local closes from application, I have a feeling it would be better to record the wish of the applications at local and remote in the state. Thus when the local application calls `.close()`, record that the local wish is for close, and if there is fatal error from remote record the remote wish is for close. If the current endpoint state is closed while wish is for open, have the client perform reconnect.

But I did not jump to implement that change without a chance for discussion. Hence this draft PR.

The `wtfnode` is there to capture with Ctrl-C what is keeping mocha from terminating.

I see there is also #263 on mocha versioning.

### CODE REVIEW

**Comment by grs** [comment]
@kohtala thank you for looking into this. For the disconnection while waiting for close, my suggested fix would be https://github.com/amqp/rhea/pull/336/commits/946fbdefa82bcba4b35599d8236601c8fa776907, i.e. the test for deciding to reconnect only needs to consider whether the connection is considered closed locally. Wdyt?  (Still having some issues getting ci to pass, though tests complete ok for me locally).

**Comment by grs** [comment]
@kohtala actually, looking a bit more into this, I think your fix is correct. The logic around this is messy in the code already and no doubt it could be more clearly expressed. However I think your fix is a strict improvement. 

Can you update your patch to change the versions run under travis, dropping 4, 6 and 8 as these seem no longer to be supported by the latest mocha and adding 12 and 14?

Thanks again for your work on this!

**Comment by kohtala** [comment]
Hi. Thank you @grs, I appreciate having this available and am glad I can give something back.

I'll proceed to make another PR later today to discuss. We've been having some issues and with the updated coverage I looked at missing test cases and I think I've found. Unfortunately my client has limited budget so I'm not sure how much I can do for this.

**Comment by kohtala** [comment]
Btw. travis is showing a banner "Please be aware travis-ci.org will be shutting down in several weeks, with all accounts migrating to travis-ci.com. Please stay tuned here for more information." I'm not familiar with the integration, so thought I mention just in case it needs some attention in the repository.

**Comment by kornys** [comment]
I suggest to migrate to gh action instead of using travis. @grs I can take care in different PR

**Comment by grs** [comment]
Thanks again @kohtala !

**Comment by grs** [comment]
@kornys, if you have the time that would be marvellous, thanks!

**Pull request merged**
