### PR TITLE
sender/receiver/session _error/_close events can occur at a wider scope if they are not handled at the right level.

### PR DESCRIPTION
**Pull request by amarzavery**

### CODE REVIEW

**Comment by amarzavery** [comment]
@grs - Am I missing any other events that can potentially be raised at a wider scope?
- Is this true only for *_error and *_close?
- What about *_open ?

**Comment by grs** [comment]
All sender/receiver events can be handled at wider scope.

**Comment by amarzavery** [comment]
Oh I see, then should I update the enum definitions for session and connection with that of sender and receiver?

One more question: Can the accepted, released, modified, rejected events also be handled at a wider scope?

**Comment by grs** [comment]
> Oh I see, then should I update the enum definitions for session and connection with that of sender and receiver?

Yes. Ideally by just inheriting them or similar, rather than copy&paste.

> One more question: Can the accepted, released, modified, rejected events also be handled at a wider scope?

Yes

**Comment by amarzavery** [comment]
I am able to use Object.assign(SessionEvents, SenderEvents, ReceiverEvents) in the js code in lib/eventTypes.js. However, there is no good way to merge enums in TS. I guess the best way to declare this in the consumer TS app is to use union types while declaring the event handler for session/connection/container. Hence closing this PR.

**Pull request closed without merging**
