### PR TITLE
Improve type definitions

### PR DESCRIPTION
**Pull request by amarzavery**

### CODE REVIEW

**Comment by amarzavery** [comment]
@grs - node.js version 4.x has ended it's LTS support cycle. Should we remove this from the travis build?

**Comment by pierreca** [comment]
WRT to dropping node v4.x can't do that without bumping the major version number. Customers in production, even if running old deprecated stuff, still rely on semantic versioning.

**Comment by amarzavery** [comment]
@pierreca - That makes sense. IMO, bumping to 0.4.0 should be fine. @grs what do you think?

**Comment by grs** [comment]
@amarzavery is there a particular reason this change needs to update mocha? If not I would be inclined to leave that out for now. I'm not opposed to dropping support for 4, but its not clear that it is really justified for this particular change, unless there is some dependency I'm missing.

**Comment by amarzavery** [comment]
@grs - I bumped the version of mocha since npm said there were some vulnerabilities in the old version of mocha. However, that has got nothing to do with the build failing for node.js version 4.x
I created a new branch from upstream/master. Installed 4.9.1 version of node.js (one used by travis). Did a clean `npm install` again and ran `npm test`. It still complains for the same thing.

Here is the log
```bash
Amars-MBP:rhea amarz$ node -v
v4.9.1
Amars-MBP:rhea amarz$ npm -v
2.15.11
Amars-MBP:rhea amarz$ npm i
@types/debug@0.0.30 node_modules/@types/debug

@types/mocha@5.2.5 node_modules/@types/mocha

require-self@0.2.1 node_modules/require-self

@types/node@8.10.29 node_modules/@types/node

minimist@1.2.0 node_modules/minimist

debug@4.0.1 node_modules/debug
└── ms@2.1.1

ws@6.0.0 node_modules/ws
└── async-limiter@1.0.0

uglify-js@3.4.9 node_modules/uglify-js
├── commander@2.17.1
└── source-map@0.6.1

ts-node@7.0.1 node_modules/ts-node
├── buffer-from@1.1.1
├── arrify@1.0.1
├── yn@2.0.0
├── make-error@1.3.5
├── diff@3.5.0
├── source-map-support@0.5.9 (source-map@0.6.1)
└── mkdirp@0.5.1 (minimist@0.0.8)

mocha@3.5.3 node_modules/mocha
├── escape-string-regexp@1.0.5
├── browser-stdout@1.3.0
├── growl@1.9.2
├── json3@3.3.2
├── he@1.1.1
├── supports-color@3.1.2 (has-flag@1.0.0)
├── commander@2.9.0 (graceful-readlink@1.0.1)
├── debug@2.6.8 (ms@2.0.0)
├── diff@3.2.0
├── mkdirp@0.5.1 (minimist@0.0.8)
├── lodash.create@3.1.1 (lodash._basecreate@3.0.3, lodash._isiterateecall@3.0.9, lodash._baseassign@3.2.0)
└── glob@7.1.1 (path-is-absolute@1.0.1, inherits@2.0.3, fs.realpath@1.0.0, once@1.4.0, inflight@1.0.6, minimatch@3.0.4)

typescript@3.0.3 node_modules/typescript

browserify@16.2.2 node_modules/browserify
├── tty-browserify@0.0.1
├── https-browserify@1.0.0
├── duplexer2@0.1.4
├── punycode@1.4.1
├── constants-browserify@1.0.0
├── inherits@2.0.3
├── path-browserify@0.0.1
├── domain-browser@1.2.0
├── os-browserify@0.3.0
├── htmlescape@1.1.1
├── util@0.10.4
├── through2@2.0.3
├── process@0.11.10
├── stream-browserify@2.0.1
├── cached-path-relative@1.0.1
├── defined@1.0.0
├── subarg@1.0.0
├── xtend@4.0.1
├── read-only-stream@2.0.0
├── querystring-es3@0.2.1
├── timers-browserify@1.4.2
├── vm-browserify@1.1.0
├── deps-sort@2.0.0
├── string_decoder@1.1.1 (safe-buffer@5.1.2)
├── concat-stream@1.6.2 (buffer-from@1.1.1, typedarray@0.0.6)
├── events@2.1.0
├── parents@1.0.1 (path-platform@0.11.15)
├── buffer@5.2.1 (ieee754@1.1.12, base64-js@1.3.0)
├── has@1.0.3 (function-bind@1.1.1)
├── console-browserify@1.1.0 (date-now@0.1.4)
├── shell-quote@1.6.1 (array-filter@0.0.1, array-map@0.0.0, jsonify@0.0.0, array-reduce@0.0.0)
├── url@0.11.0 (punycode@1.3.2, querystring@0.2.0)
├── readable-stream@2.3.6 (process-nextick-args@2.0.0, safe-buffer@5.1.2, util-deprecate@1.0.2, core-util-is@1.0.2, isarray@1.0.0)
├── labeled-stream-splicer@2.0.1 (isarray@2.0.4, stream-splicer@2.0.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── assert@1.4.1 (util@0.10.3)
├── shasum@1.0.2 (json-stable-stringify@0.0.1, sha.js@2.4.11)
├── glob@7.1.3 (path-is-absolute@1.0.1, fs.realpath@1.0.0, once@1.4.0, inflight@1.0.6, minimatch@3.0.4)
├── stream-http@2.8.3 (builtin-status-codes@3.0.0, to-arraybuffer@1.0.1)
├── browserify-zlib@0.2.0 (pako@1.0.6)
├── JSONStream@1.3.4 (through@2.3.8, jsonparse@1.3.1)
├── syntax-error@1.4.0 (acorn-node@1.5.2)
├── browser-pack@6.1.0 (safe-buffer@5.1.2, umd@3.0.3, combine-source-map@0.8.0)
├── browser-resolve@1.11.3 (resolve@1.1.7)
├── resolve@1.8.1 (path-parse@1.0.6)
├── insert-module-globals@7.2.0 (path-is-absolute@1.0.1, is-buffer@1.1.6, undeclared-identifiers@1.1.2, acorn-node@1.5.2, combine-source-map@0.8.0)
├── crypto-browserify@3.12.0 (randomfill@1.0.4, randombytes@2.0.6, create-hmac@1.1.7, pbkdf2@3.0.16, diffie-hellman@5.0.3, create-hash@1.2.0, create-ecdh@4.0.3, browserify-cipher@1.0.1, browserify-sign@4.0.4, public-encrypt@4.0.2)
└── module-deps@6.1.0 (stream-combiner2@1.1.1, detective@5.1.0)

eslint@4.19.1 node_modules/eslint
├── path-is-inside@1.0.2
├── natural-compare@1.4.0
├── is-resolvable@1.1.0
├── imurmurhash@0.1.4
├── ignore@3.3.10
├── strip-json-comments@2.0.1
├── pluralize@7.0.0
├── globals@11.7.0
├── eslint-visitor-keys@1.0.0
├── functional-red-black-tree@1.0.1
├── esutils@2.0.2
├── semver@5.5.1
├── progress@2.0.0
├── doctrine@2.1.0
├── text-table@0.2.0
├── json-stable-stringify-without-jsonify@1.0.1
├── strip-ansi@4.0.0 (ansi-regex@3.0.0)
├── regexpp@1.1.0
├── debug@3.2.5 (ms@2.1.1)
├── esquery@1.0.1 (estraverse@4.2.0)
├── levn@0.3.0 (type-check@0.3.2, prelude-ls@1.1.2)
├── optionator@0.8.2 (fast-levenshtein@2.0.6, type-check@0.3.2, wordwrap@1.0.0, deep-is@0.1.3, prelude-ls@1.1.2)
├── eslint-scope@3.7.3 (esrecurse@4.2.1, estraverse@4.2.0)
├── minimatch@3.0.4 (brace-expansion@1.1.11)
├── glob@7.1.3 (path-is-absolute@1.0.1, inherits@2.0.3, fs.realpath@1.0.0, once@1.4.0, inflight@1.0.6)
├── require-uncached@1.0.3 (resolve-from@1.0.1, caller-path@0.1.0)
├── babel-code-frame@6.26.0 (js-tokens@3.0.2, chalk@1.1.3)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── cross-spawn@5.1.0 (shebang-command@1.2.0, lru-cache@4.1.3, which@1.3.1)
├── chalk@2.4.1 (escape-string-regexp@1.0.5, supports-color@5.5.0, ansi-styles@3.2.1)
├── concat-stream@1.6.2 (buffer-from@1.1.1, inherits@2.0.3, typedarray@0.0.6, readable-stream@2.3.6)
├── table@4.0.2 (string-width@2.1.1, slice-ansi@1.0.0, ajv-keywords@2.1.1)
├── espree@3.5.4 (acorn@5.7.3, acorn-jsx@3.0.1)
├── file-entry-cache@2.0.0 (object-assign@4.1.1, flat-cache@1.3.0)
├── js-yaml@3.12.0 (esprima@4.0.1, argparse@1.0.10)
├── inquirer@3.3.0 (ansi-escapes@3.1.0, rx-lite-aggregates@4.0.8, cli-width@2.2.0, rx-lite@4.0.8, through@2.3.8, figures@2.0.0, mute-stream@0.0.7, string-width@2.1.1, run-async@2.3.0, cli-cursor@2.1.0, external-editor@2.2.0)
├── ajv@5.5.2 (fast-deep-equal@1.1.0, co@4.6.0, json-schema-traverse@0.3.1, fast-json-stable-stringify@2.0.0)
└── lodash@4.17.11

istanbul@1.1.0-alpha.1 node_modules/istanbul
├── abbrev@1.0.9
├── async@1.5.2
├── wordwrap@1.0.0
├── nopt@3.0.6
├── which@1.3.1 (isexe@2.0.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── js-yaml@3.12.0 (esprima@4.0.1, argparse@1.0.10)
└── istanbul-api@1.3.7 (istanbul-lib-coverage@1.2.1, once@1.4.0, istanbul-lib-report@1.1.5, fileset@2.0.3, istanbul-lib-hook@1.2.2, istanbul-lib-source-maps@1.2.6, istanbul-reports@1.5.1, async@2.6.1, istanbul-lib-instrument@1.10.2)
Amars-MBP:rhea amarz$ npm list mocha
rhea@0.3.1 /Users/amarz/sdk/rh/rhea
└── mocha@3.5.3

Amars-MBP:rhea amarz$ npm list typescript
rhea@0.3.1 /Users/amarz/sdk/rh/rhea
└── typescript@3.0.3

Amars-MBP:rhea amarz$ npm list ts-node
rhea@0.3.1 /Users/amarz/sdk/rh/rhea
└── ts-node@7.0.1

Amars-MBP:rhea amarz$ npm test

> rhea@0.3.1 test /Users/amarz/sdk/rh/rhea
> npm run lint && npm run tsc && mocha -r ts-node/register ./test/*.ts


> rhea@0.3.1 lint /Users/amarz/sdk/rh/rhea
> eslint lib/*.js


> rhea@0.3.1 tsc /Users/amarz/sdk/rh/rhea
> tsc

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/amarz/sdk/rh/rhea/node_modules/debug/src/index.js:9:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/amarz/sdk/rh/rhea/lib/log.js:18:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/amarz/sdk/rh/rhea/lib/connection.js:20:11)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/amarz/sdk/rh/rhea/lib/container.js:18:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/amarz/sdk/rh/rhea/test/connections.ts:18:1)
    at Module._compile (module.js:409:26)
    at Module.m._compile (/Users/amarz/sdk/rh/rhea/node_modules/ts-node/src/index.ts:439:23)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/amarz/sdk/rh/rhea/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /Users/amarz/sdk/rh/rhea/node_modules/mocha/lib/mocha.js:231:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/amarz/sdk/rh/rhea/node_modules/mocha/lib/mocha.js:228:14)
    at Mocha.run (/Users/amarz/sdk/rh/rhea/node_modules/mocha/lib/mocha.js:514:10)
    at Object.<anonymous> (/Users/amarz/sdk/rh/rhea/node_modules/mocha/bin/_mocha:480:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
npm ERR! Test failed.  See above for more details.
```

**Comment by amarzavery** [comment]
I just restarted an old passing Travis CI build for one of the previous commits that was checked into master and the CI failed. Here is the [link](https://travis-ci.org/amqp/rhea/jobs/426641711). It was passing few days ago. Here is the [link](https://github.com/amqp/rhea/commits/master) to the previous commits. IMHO, we should drop support for 4.x versions of node.js and bump the version of package to 0.4.0. Should that be fine?

**Comment by amarzavery** [comment]
@grs- Thanks a ton for all the help. And the CI is green. I have also bumped the package version to 0.3.2. If everything looks good can we squash-merge this PR.

**Comment by amarzavery** [comment]
@grs - Once, the PR is merged, please publish the package as well. This will enable me to ship the first version of rhea-promise :).

**Comment by grs** [comment]
@amarzavery did you mean to close this?

**Comment by grs** [comment]
ignore, see new pr now

**Comment by amarzavery** [comment]
I am a novice with git rebase. I did resolve the conflicts but somehow the interactive rebase tripped me over :(

**Pull request closed without merging**
